login: &login
  adapter: mysql2
  host: localhost
  port: 3306
  username: root
  password: 

development:
  database: talent_development
  <<: *login

test: &test
  database: talent_test
  <<: *login

cucumber:
  <<: *test

production:
  database: talent_production
  <<: *login